[server]
port=9909
timeOut=6000
optLinger=false

; NO_ET=0
; HTTP_ET=1
; LISTEN_ET=2
; ALL_ET=3
trigMode=3 

srcDir=/home/deng/WebServer/resources/

[thread]
threadNum=4

[log]
path=./logFiles
suffix=.log

; debug=0
; info=1
; warn=2
; error=3
level=3
queueSize=1024

[database]
host=localhost
port=3306
userName=deng
password=deng
dbName=WebServer
maxDBConn=16

